baseURL = "https://kyktommy.github.io/"
languageCode = "en-us"
title = "Kyk's Blog"
theme = "hugo-theme-cactus-plus"

pygmentsUseClasses = true

[params]
  description = "@kyktommy"
  [params.links]
    "Setup" = "/setup"
    "Awesomes" = "https://github.com/kyktommy/awesomes"
    "Learn source code" = "https://kyktommy.github.io/learn-source-code/"
