baseURL = "https://kyktommy.github.io/"
languageCode = "en-us"
title = "kyk's blog"
theme = "paper"

pygmentsUseClasses = true

[params]
  color = "light"
  github = "kyktommy"
  name = "kyktommy"
  avatar = "https://avatars.githubusercontent.com/u/508813?v=4"
  bio = "不要輕易放過自己, 就是對今天責負的態度"
  [params.links]
    "My setup" = "/my-setup"
    "Awesomes" = "https://github.com/kyktommy/awesomes"
    "Learn source code" = "https://kyktommy.github.io/learn-source-code/"
